name: 🧠 Metrics

on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata

          plugin_languages: yes
          plugin_isocalendar: yes
          plugin_stars: yes
          plugin_lines: yes
          plugin_followup: yes


✨ Add metrics workflow

